### ISSUE TITLE
How to enable OPC UA on HAAS machine

### ISSUE THREAD

**Issue by BadriNordin** [pkoprov/Haas-Data-Collection#1]
Hi, just curious how do we enable OPC UA on HAAS machines, I have been going through the HAAS website documentations but I could not find any documentation about OPC UA

**Comment by pkoprov** [comment]
You are totally right. There is no OPC UA client on Haas NGC. You need to write your own. Even the MTConnect server is using Q-codes to poll the NGC.

**Comment by BadriNordin** [comment]
i see, just curious do you have any experience developing OPC UA client on other HAAS machines? If yes, is it possible to make the client adaptable to other models or does it take too much customization?

**Comment by nobrainer-de** [comment]
Just use MTConnect. there is already a solution for mtconnect to MQTT open source

**Comment by pkoprov** [comment]
> i see, just curious do you have any experience developing OPC UA client on other HAAS machines? If yes, is it possible to make the client adaptable to other models or does it take too much customization?

I did not finish this work, but it is doable. There is a Python library for the OPC UA client and server. You would still need to send Q-codes to get the information you need. If you will be using Haas machines with New Generation Controller then it will be the same for any machine with slight correction according to the machine you have. For example, the ST-10 lathe does not have a y-axis, but you still can send Q-codes about the Y-axis load and coordinates, but NGC will return 0 values.

**Comment by BadriNordin** [comment]
Alright many thankss
